version: '3.8'

services:
    database:
        image: postgres:14
        environment:
            - POSTGRES_DB=dish_db
            - POSTGRES_USER=admin
            - POSTGRES_PASSWORD=admin
        healthcheck:
            test: ["CMD", "pg_isready", "-U", "admin", "-d", "dish_db"]
            interval: 10s

    django:
        build: .
        ports:
            - 8000:8000
        depends_on:
            database:
                condition: service_healthy
        command: bash -c "python manage.py migrate && 
                 python manage.py loaddata db_backup.json &&
                 python manage.py runserver 0.0.0.0:8000"


