# Generated by Django 4.1.6 on 2023-03-16 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_project_test_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='test_url',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
